{
 "title": "Device Overview",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Device",
    "query": "SHOW TAG VALUES WITH KEY = \"source\""
   }
  ]
 },
 "panels": [
  {
   "title": "Interface input/output",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "alias": "$tag_name $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "interfaces",
     "select": [
      [
       { "params": [ "counters/in_octets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "8s" ], "type": "non_negative_derivative" },
       { "params": [ "RX" ], "type": "alias" }
      ],
      [
       { "params": [ "counters/out_octets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "8s" ], "type": "non_negative_derivative" },
       { "params": [ "TX" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "source::tag", "operator": "=~", "value": "/^$Device$/" }
     ]
    }
   ]
  },
  {
   "title": "Optical power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "alias": "$tag_name $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "optics",
     "select": [
      [
       { "params": [ "state/input_power/instant" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "RX" ], "type": "alias" }
      ],
      [
       { "params": [ "state/output_power/instant" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "TX" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "source::tag", "operator": "=~", "value": "/^$Device$/" }
     ]
    }
   ]
  },
  {
   "title": "Processor utilization",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "instant" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source::tag", "operator": "=~", "value": "/^$Device$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory utilization",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "platform-state",
     "query": "SELECT mean(\"memory/utilized\") / mean(\"memory/available\") FROM \"platform-state\" WHERE (\"source\"::tag =~ /^$Device$/) AND $timeFilter GROUP BY time($__interval), \"name\"::tag fill(null)",
     "select": [
      [
       { "params": [ "memory/utilized" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source::tag", "operator": "=~", "value": "/^$Device$/" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "platform-state",
     "query": "SELECT mean(\"memory/utilized\") / mean(\"memory/available\") FROM \"platform-state\" WHERE (\"source\"::tag =~ /^$Device$/) AND $timeFilter GROUP BY time($__interval), \"name\"::tag fill(null)",
     "select": [
      [
       { "params": [ "temperature/instant" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*1.8 +32" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "source::tag", "operator": "=~", "value": "/^$Device$/" }
     ]
    }
   ]
  },
  {
   "title": "Interfaces",
   "type": "table",
   "gridPos": { "h": 20, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name::tag" ], "type": "tag" }
     ],
     "measurement": "interfaces",
     "select": [
      [
       { "params": [ "description" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Description" ], "type": "alias" }
      ],
      [
       { "params": [ "oper_status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "State" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "source::tag", "operator": "=~", "value": "/^$Device$/" }
     ]
    }
   ]
  },
  {
   "title": "Platform",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name::tag" ], "type": "tag" }
     ],
     "measurement": "platform-state",
     "select": [
      [
       { "params": [ "description" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Description" ], "type": "alias" }
      ],
      [
       { "params": [ "oper_status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Status" ], "type": "alias" }
      ],
      [
       { "params": [ "serial_no" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Serial" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "source::tag", "operator": "=~", "value": "/^$Device$/" }
     ]
    }
   ]
  }
 ]
}