{
 "title": "Environment Overview",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_source",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "instant" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_source",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "platform-state",
     "query": "SELECT last(\"memory/utilized\") / last(\"memory/available\") FROM \"platform-state\" WHERE $timeFilter GROUP BY time($__interval), \"source\"::tag fill(null)",
     "select": [
      [
       { "params": [ "memory/utilized" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Inlet Temperature",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_source $tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source::tag" ], "type": "tag" },
      { "params": [ "name::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "platform-state",
     "select": [
      [
       { "params": [ "temperature/instant" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* 1.8 + 32" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "name::tag", "operator": "=~", "value": "/Inlet/" }
     ]
    }
   ]
  },
  {
   "title": "Warning status",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "alias": "$tag_source $tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source::tag" ], "type": "tag" },
      { "params": [ "name::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "platform-state",
     "select": [
      [
       { "params": [ "oper_status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "oper_status", "operator": "!=", "value": "ACTIVE" }
     ]
    }
   ]
  }
 ]
}