{
 "title": "Telemetry Stack",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Database stats",
   "type": "stat",
   "gridPos": { "h": 24, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "influxdb_database",
     "select": [
      [
       { "params": [ "numMeasurements" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Measurements" ], "type": "alias" }
      ],
      [
       { "params": [ "numSeries" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Series" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "Disk usage - $tag_database",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "database::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "influxdb_shard",
     "select": [
      [
       { "params": [ "diskBytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "database::tag", "operator": "!=", "value": "_internal" }
     ]
    }
   ]
  },
  {
   "title": "Telegraf Metrics Gathered/Written",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 0 },
   "targets": [
    {
     "alias": "$tag_input gathered",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "input::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "internal_gather",
     "select": [
      [
       { "params": [ "metrics_gathered" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "alias": "$tag_output written",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "output::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "internal_write",
     "select": [
      [
       { "params": [ "metrics_written" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Telegraf Metrics Gather/Write time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_input gather time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "input::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "internal_gather",
     "select": [
      [
       { "params": [ "gather_time_ns" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "alias": "$tag_alias write time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "alias::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "internal_write",
     "select": [
      [
       { "params": [ "write_time_ns" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Database writes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "influxdb_httpd",
     "select": [
      [
       { "params": [ "pointsWrittenOK" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "OK" ], "type": "alias" }
      ],
      [
       { "params": [ "pointsWrittenDropped" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Dropped" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}